-- analytics.stg_events
-- One normalized row per raw_events_full event. Raw values preserved.
-- Missing GTM fields are NULL until GTM_CHANGES.md is applied, then
-- COALESCE the new columns in the SELECT list (do not drop URL extracts).

CREATE OR REPLACE VIEW `stape-analytics-487802.analytics.stg_events` AS
WITH raw AS (
  SELECT
    r.timestamp AS event_timestamp_millis,
    TIMESTAMP_MILLIS(r.timestamp) AS event_timestamp,
    DATE(TIMESTAMP_MILLIS(r.timestamp), "America/Los_Angeles") AS event_date,
    DATE(r._PARTITIONTIME) AS ingestion_date,
    r.event_name,
    r.event_id,
    r.source_client,
    NULLIF(r.transaction_id, "") AS transaction_id,
    NULLIF(r.user_id, "") AS shopify_customer_id,
    NULLIF(r.client_id, "") AS client_id,
    NULLIF(CAST(r.ga_session_id AS STRING), "") AS ga_session_id,
    r.ga_session_number,
    r.page_location,
    r.page_referrer,
    r.gclid AS gclid_col,
    r.gbraid AS gbraid_col,
    r.wbraid AS wbraid_col,
    r.dclid AS dclid_col,
    r.value,
    r.currency,
    r.tax,
    r.shipping,
    r.coupon,
    r.items,
    r.user_agent
  FROM `stape-analytics-487802.stape_data.raw_events_full` AS r
),
extracted AS (
  SELECT
    raw.*,
    NET.HOST(raw.page_location) AS page_host,
    REGEXP_EXTRACT(raw.page_location, r"https?://[^/]+(/[^?]*)") AS page_path,
    NET.HOST(raw.page_referrer) AS referrer_host,
    NULLIF(REGEXP_EXTRACT(raw.page_location, r"[?&]utm_source=([^&]+)"), "") AS url_utm_source,
    NULLIF(REGEXP_EXTRACT(raw.page_location, r"[?&]utm_medium=([^&]+)"), "") AS url_utm_medium,
    NULLIF(REGEXP_EXTRACT(raw.page_location, r"[?&]utm_campaign=([^&]+)"), "") AS url_utm_campaign,
    NULLIF(REGEXP_EXTRACT(raw.page_location, r"[?&]utm_content=([^&]+)"), "") AS url_utm_content,
    NULLIF(REGEXP_EXTRACT(raw.page_location, r"[?&]utm_term=([^&]+)"), "") AS url_utm_term,
    NULLIF(REGEXP_EXTRACT(raw.page_location, r"[?&]gclid=([^&]+)"), "") AS url_gclid,
    NULLIF(REGEXP_EXTRACT(raw.page_location, r"[?&]gbraid=([^&]+)"), "") AS url_gbraid,
    NULLIF(REGEXP_EXTRACT(raw.page_location, r"[?&]wbraid=([^&]+)"), "") AS url_wbraid,
    NULLIF(REGEXP_EXTRACT(raw.page_location, r"[?&]fbclid=([^&]+)"), "") AS url_fbclid,
    NULLIF(REGEXP_EXTRACT(raw.page_location, r"[?&]msclkid=([^&]+)"), "") AS url_msclkid,
    NULLIF(REGEXP_EXTRACT(raw.page_location, r"[?&]ttclid=([^&]+)"), "") AS url_ttclid
  FROM raw
)
SELECT
  event_timestamp_millis,
  event_timestamp,
  event_date,
  ingestion_date,
  event_name,
  event_id,
  source_client,
  transaction_id,
  CAST(NULL AS STRING) AS stape_user_id,
  CAST(NULL AS STRING) AS gn_uid,
  shopify_customer_id,
  CAST(NULL AS STRING) AS hashed_email,
  client_id,
  ga_session_id,
  ga_session_number,
  page_location,
  page_path,
  page_referrer,
  referrer_host,
  url_utm_source AS raw_source,
  url_utm_medium AS raw_medium,
  url_utm_campaign AS raw_campaign,
  url_utm_content AS raw_content,
  url_utm_term AS raw_term,
  page_referrer AS raw_referrer,
  url_utm_source AS utm_source,
  url_utm_medium AS utm_medium,
  url_utm_campaign AS utm_campaign,
  url_utm_content AS utm_content,
  url_utm_term AS utm_term,
  COALESCE(NULLIF(gclid_col, ""), url_gclid) AS gclid,
  COALESCE(NULLIF(gbraid_col, ""), url_gbraid) AS gbraid,
  COALESCE(NULLIF(wbraid_col, ""), url_wbraid) AS wbraid,
  NULLIF(dclid_col, "") AS dclid,
  url_fbclid AS fbclid,
  url_msclkid AS msclkid,
  url_ttclid AS ttclid,
  TO_JSON_STRING(STRUCT(
    url_gclid AS gclid,
    url_gbraid AS gbraid,
    url_wbraid AS wbraid,
    url_fbclid AS fbclid,
    url_msclkid AS msclkid,
    url_ttclid AS ttclid
  )) AS raw_click_ids,
  value,
  currency,
  tax,
  shipping,
  coupon,
  items,
  LOWER(IFNULL(event_name, "")) = "purchase" AND transaction_id IS NOT NULL AS is_purchase,
  LOWER(IFNULL(event_name, "")) = "page_view" AS is_page_view,
  LOWER(IFNULL(event_name, "")) = "session_start" AS is_session_start,
  ingestion_date > DATE_ADD(event_date, INTERVAL 1 DAY) AS is_late_event,
  user_agent
FROM extracted;
